### ISSUE TITLE
Multipart fails to download CodeChickenLib even if it's there

### ISSUE THREAD

**Issue by Roadhog360** [GTNewHorizons/CodeChickenCore#13]
Note: This is a standalone report, that probably is for Multipart, but could be an issue on CodeChickenCore's end too. I am not exactly sure where this issue comes from, but both repos do not have issue trackers.
bombcar told me to put it here and he'd move it later

### Your GTNH Discord Username

Roadhog360

### Your Pack Version

n/a

### Your Server

n/a

### Java Version

Java 8

### Type of Server

None

### Your Expectation

When attempting to run Multipart in the dev env with CodeChickenCore and CodeChickenLib both at 1.2.0.
This happens with Multipart GTNH version 1.4.1 or 1.4.3, haven't tested other versions but those probably also get the bug.

It's worth noting that I chose 1.4.1 and 1.4.3 specifically because I made the changes in 1.4.3, so I tried 1.4.1 to ensure that **this bug is NOT caused by any changes in my code!**

Note this is taking place with dev env mods, this might be a dev env issue? See "the reality" for more info

Expected result:
Multipart successfully downloads CodeChickenLib and puts it in `mods/1.7.10`

### The Reality

The following pop up appears regardless of CodeChickenLib version present, EVEN IF I DOWNLOAD IT MYSELF IT STILL TRIES TO GET THIS VERSION! The game will not launch unless I remove Multipart or downgrade to the latest Non-GTNH build

CB's DepLoader was unable to download required library https://github.com/GTNewHorizons/CodeChickenLib/releases/download/1.1.5.5/CodeChickenLib-1.7.10-1.1.5.5-dev.jar Check your internet connection and try restarting or download it manually from https://github.com/GTNewHorizons/CodeChickenLib/releases/download/1.1.5.5//https://github.com/GTNewHorizons/CodeChickenLib/releases/download/1.1.5.5/CodeChickenLib-1.7.10-1.1.5.5-dev.jar and put it in your mods folder 

This is possibly a dev env issue, as this seems to happen within my dev environment for [Et Futurum Requiem](https://github.com/Roadhog360/Et-Futurum-Requiem) when adding CodeChickenCore and Multipart to the `mods` folder, and CodeChickenLib to the `mods.1.7.10` folder, and is not present in a production environment. I made sure all versions are the `dev` jars too

### Your Proposal

Fix the obvious broken download and broken dependency check

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I suspect dev is making it mad though it should work even so

**Comment by Roadhog360** [comment]
Yeah, weird. I wonder if CCC's deploader should just be deprecated or at least deactivated in dev.

**Comment by Roadhog360** [comment]
Update: Tried renaming the 1.2.0 jar to `CodeChickenLib-1.1.5.5-dev.jar` to see if that's work.

Result:
CCC deploader deleted it, downloaded a jar named `CodeChickenLib-1.1.6-dev.jar` and then complained that it couldn't download 1.1.5.5 with the same popup error as above.

What

**Comment by bombcar** [comment]
Those are all super old, too

**Comment by bombcar** [comment]
Weird, I cannot get this to happen with tag/1.4.3 or head (though if I update dependencies to 1.2.0 it blows up in Scala compilation)

```
[Error] /Users/bombcar/Documents/GitHub/ForgeMultipart/src/main/scala/codechicken/microblock/BlockMicroMaterial.scala:27:29: value pipeline is not a member of object codechicken.lib.render.CCRenderState
[Error] /Users/bombcar/Documents/GitHub/ForgeMultipart/src/main/scala/codechicken/microblock/BlockMicroMaterial.scala:39:33: value lightMatrix is not a member of object codechicken.lib.render.CCRenderState
[Error] /Users/bombcar/Documents/GitHub/ForgeMultipart/src/main/scala/codechicken/microblock/BlockMicroMaterial.scala:88:31: value lightMatrix is not a member of object codechicken.lib.render.CCRenderState
[Error] /Users/bombcar/Documents/GitHub/ForgeMultipart/src/main/scala/codechicken/microblock/BlockMicroMaterial.scala:90:23: value lightMatrix is not a member of object codechicken.lib.render.CCRenderState
```
which I don't know how to fix

**Comment by Roadhog360** [comment]
Just one cryptic error after another...
![image](https://github.com/GTNewHorizons/CodeChickenCore/assets/11903511/b4106bbb-7390-4e12-822b-37f81315786b)

**Comment by Caedis** [comment]
Is something shadowing it and something else is screwing up?

**Comment by bombcar** [comment]
> Is something shadowing it and something else is screwing up?

Nah it was in dependencies.info. Linked PR fixes that and ccl compat

**Comment by Roadhog360** [comment]
@bombcar OK; this works! Ty!
One more minor thing though; which still might be a dev issue. In 1.7.10 CodeChickenLib 1.1.6 is downloaded which causes a crash with rendering multipart blocks. Suggested fix is to make it download 1.2.0 instead, using 1.2.0 works for me.
Attached below is the aforementioned crash.
[crash-2024-01-03_14.03.08-client.txt](https://github.com/GTNewHorizons/CodeChickenCore/files/13822960/crash-2024-01-03_14.03.08-client.txt)

**Comment by bombcar** [comment]
FMP won’t download anything anymore, and it needs 1.2.0

**Comment by bombcar** [comment]
(Note ccc itself may do downloads. Will check.

**Comment by bombcar** [comment]
ah it was NEI, which pulled in 1.1.6 at times
